-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Moderation/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE moderation (
  mod_id SERIAL NOT NULL,
  mod_timestamp TIMESTAMPTZ NOT NULL,
  mod_user INT DEFAULT 0 NOT NULL,
  mod_user_text TEXT NOT NULL,
  mod_cur_id INT NOT NULL,
  mod_namespace INT DEFAULT 0 NOT NULL,
  mod_title TEXT DEFAULT '' NOT NULL,
  mod_comment TEXT DEFAULT '' NOT NULL,
  mod_minor SMALLINT DEFAULT 0 NOT NULL,
  mod_bot SMALLINT DEFAULT 0 NOT NULL,
  mod_new SMALLINT DEFAULT 0 NOT NULL,
  mod_last_oldid INT DEFAULT 0 NOT NULL,
  mod_ip TEXT DEFAULT '' NOT NULL,
  mod_old_len INT DEFAULT NULL,
  mod_new_len INT DEFAULT NULL,
  mod_header_xff TEXT DEFAULT '',
  mod_header_ua TEXT DEFAULT '',
  mod_tags TEXT DEFAULT NULL,
  mod_preload_id TEXT NOT NULL,
  mod_rejected SMALLINT DEFAULT 0 NOT NULL,
  mod_rejected_by_user INT DEFAULT 0 NOT NULL,
  mod_rejected_by_user_text TEXT DEFAULT NULL,
  mod_rejected_batch SMALLINT DEFAULT 0 NOT NULL,
  mod_rejected_auto SMALLINT DEFAULT 0 NOT NULL,
  mod_preloadable INT DEFAULT 0 NOT NULL,
  mod_conflict SMALLINT DEFAULT 0 NOT NULL,
  mod_merged_revid INT DEFAULT 0 NOT NULL,
  mod_text TEXT DEFAULT NULL,
  mod_stash_key TEXT DEFAULT NULL,
  mod_type TEXT DEFAULT 'edit' NOT NULL,
  mod_page2_namespace INT DEFAULT 0 NOT NULL,
  mod_page2_title TEXT DEFAULT '' NOT NULL,
  PRIMARY KEY(mod_id)
);

CREATE UNIQUE INDEX moderation_load ON moderation (
  mod_preloadable, mod_type, mod_namespace,
  mod_title, mod_preload_id
);

CREATE INDEX moderation_approveall ON moderation (
  mod_user_text, mod_rejected, mod_conflict
);

CREATE INDEX moderation_rejectall ON moderation (
  mod_user_text, mod_rejected, mod_merged_revid
);

CREATE INDEX moderation_folder_pending ON moderation (
  mod_rejected, mod_merged_revid, mod_timestamp
);

CREATE INDEX moderation_folder_rejected ON moderation (
  mod_rejected, mod_rejected_auto,
  mod_merged_revid, mod_timestamp
);

CREATE INDEX moderation_folder_merged ON moderation (mod_merged_revid, mod_timestamp);

CREATE INDEX moderation_folder_spam ON moderation (
  mod_rejected_auto, mod_timestamp
);

CREATE INDEX moderation_signup ON moderation (mod_preload_id, mod_preloadable);


CREATE TABLE moderation_block (
  mb_id SERIAL NOT NULL,
  mb_address TEXT NOT NULL,
  mb_user INT DEFAULT 0 NOT NULL,
  mb_by INT DEFAULT 0 NOT NULL,
  mb_by_text TEXT DEFAULT '' NOT NULL,
  mb_timestamp TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(mb_id)
);

CREATE UNIQUE INDEX moderation_block_address ON moderation_block (mb_address);
