-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Moderation/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/moderation (
  mod_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  mod_timestamp BLOB NOT NULL, mod_user INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  mod_user_text BLOB NOT NULL, mod_cur_id INTEGER UNSIGNED NOT NULL,
  mod_namespace INTEGER DEFAULT 0 NOT NULL,
  mod_title BLOB DEFAULT '' NOT NULL,
  mod_comment BLOB DEFAULT '' NOT NULL,
  mod_minor SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
  mod_bot SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
  mod_new SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
  mod_last_oldid INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  mod_ip BLOB DEFAULT '' NOT NULL, mod_old_len INTEGER DEFAULT NULL,
  mod_new_len INTEGER DEFAULT NULL,
  mod_header_xff BLOB DEFAULT '', mod_header_ua BLOB DEFAULT '',
  mod_tags BLOB DEFAULT NULL, mod_preload_id BLOB NOT NULL,
  mod_rejected SMALLINT DEFAULT 0 NOT NULL,
  mod_rejected_by_user INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  mod_rejected_by_user_text BLOB DEFAULT NULL,
  mod_rejected_batch SMALLINT DEFAULT 0 NOT NULL,
  mod_rejected_auto SMALLINT DEFAULT 0 NOT NULL,
  mod_preloadable INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  mod_conflict SMALLINT DEFAULT 0 NOT NULL,
  mod_merged_revid INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  mod_text BLOB DEFAULT NULL, mod_stash_key BLOB DEFAULT NULL,
  mod_type BLOB DEFAULT 'edit' NOT NULL,
  mod_page2_namespace INTEGER DEFAULT 0 NOT NULL,
  mod_page2_title BLOB DEFAULT '' NOT NULL
);

CREATE UNIQUE INDEX moderation_load ON /*_*/moderation (
  mod_preloadable, mod_type, mod_namespace,
  mod_title, mod_preload_id
);

CREATE INDEX moderation_approveall ON /*_*/moderation (
  mod_user_text, mod_rejected, mod_conflict
);

CREATE INDEX moderation_rejectall ON /*_*/moderation (
  mod_user_text, mod_rejected, mod_merged_revid
);

CREATE INDEX moderation_folder_pending ON /*_*/moderation (
  mod_rejected, mod_merged_revid, mod_timestamp
);

CREATE INDEX moderation_folder_rejected ON /*_*/moderation (
  mod_rejected, mod_rejected_auto,
  mod_merged_revid, mod_timestamp
);

CREATE INDEX moderation_folder_merged ON /*_*/moderation (mod_merged_revid, mod_timestamp);

CREATE INDEX moderation_folder_spam ON /*_*/moderation (
  mod_rejected_auto, mod_timestamp
);

CREATE INDEX moderation_signup ON /*_*/moderation (mod_preload_id, mod_preloadable);


CREATE TABLE /*_*/moderation_block (
  mb_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  mb_address BLOB NOT NULL, mb_user INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  mb_by INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  mb_by_text BLOB DEFAULT '' NOT NULL,
  mb_timestamp BLOB NOT NULL
);

CREATE UNIQUE INDEX moderation_block_address ON /*_*/moderation_block (mb_address);
