-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Moderation/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/moderation (
  mod_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  mod_timestamp VARBINARY(14) NOT NULL,
  mod_user INT UNSIGNED DEFAULT 0 NOT NULL,
  mod_user_text VARBINARY(255) NOT NULL,
  mod_cur_id INT UNSIGNED NOT NULL,
  mod_namespace INT DEFAULT 0 NOT NULL,
  mod_title VARBINARY(255) DEFAULT '' NOT NULL,
  mod_comment VARBINARY(255) DEFAULT '' NOT NULL,
  mod_minor TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  mod_bot TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  mod_new TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  mod_last_oldid INT UNSIGNED DEFAULT 0 NOT NULL,
  mod_ip VARBINARY(40) DEFAULT '' NOT NULL,
  mod_old_len INT DEFAULT NULL,
  mod_new_len INT DEFAULT NULL,
  mod_header_xff VARBINARY(255) DEFAULT '',
  mod_header_ua VARBINARY(255) DEFAULT '',
  mod_tags BLOB DEFAULT NULL,
  mod_preload_id VARBINARY(256) NOT NULL,
  mod_rejected TINYINT DEFAULT 0 NOT NULL,
  mod_rejected_by_user INT UNSIGNED DEFAULT 0 NOT NULL,
  mod_rejected_by_user_text VARBINARY(255) DEFAULT NULL,
  mod_rejected_batch TINYINT DEFAULT 0 NOT NULL,
  mod_rejected_auto TINYINT DEFAULT 0 NOT NULL,
  mod_preloadable INT UNSIGNED DEFAULT 0 NOT NULL,
  mod_conflict TINYINT DEFAULT 0 NOT NULL,
  mod_merged_revid INT UNSIGNED DEFAULT 0 NOT NULL,
  mod_text MEDIUMBLOB DEFAULT NULL,
  mod_stash_key VARBINARY(255) DEFAULT NULL,
  mod_type VARBINARY(16) DEFAULT 'edit' NOT NULL,
  mod_page2_namespace INT DEFAULT 0 NOT NULL,
  mod_page2_title VARBINARY(255) DEFAULT '' NOT NULL,
  UNIQUE INDEX moderation_load (
    mod_preloadable, mod_type, mod_namespace,
    mod_title, mod_preload_id
  ),
  INDEX moderation_approveall (
    mod_user_text, mod_rejected, mod_conflict
  ),
  INDEX moderation_rejectall (
    mod_user_text, mod_rejected, mod_merged_revid
  ),
  INDEX moderation_folder_pending (
    mod_rejected, mod_merged_revid, mod_timestamp
  ),
  INDEX moderation_folder_rejected (
    mod_rejected, mod_rejected_auto,
    mod_merged_revid, mod_timestamp
  ),
  INDEX moderation_folder_merged (mod_merged_revid, mod_timestamp),
  INDEX moderation_folder_spam (
    mod_rejected_auto, mod_timestamp
  ),
  INDEX moderation_signup (mod_preload_id, mod_preloadable),
  PRIMARY KEY(mod_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/moderation_block (
  mb_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  mb_address TINYBLOB NOT NULL,
  mb_user INT UNSIGNED DEFAULT 0 NOT NULL,
  mb_by INT UNSIGNED DEFAULT 0 NOT NULL,
  mb_by_text VARBINARY(255) DEFAULT '' NOT NULL,
  mb_timestamp BINARY(14) NOT NULL,
  UNIQUE INDEX moderation_block_address (
    mb_address(255)
  ),
  PRIMARY KEY(mb_id)
) /*$wgDBTableOptions*/;
